//program for linear search in an array.
#include<iostream>
#include<stdlib.h>
using namespace std;
int main()
{
	int i,z;
	int found =0;
	int array[100];
	
	for ( i=0;i<100;i++)
	{
		array[i] = rand(); //array will be populated by random numbers generated by rand function.
	}
	    
	    cout<<"enter value to serach in array: "<<endl;
	    cin>>z;
	// loop search the array
		for ( i=0;i<100;i++)
	{
		if(array[i] == z)
		{
			found = 1;
			break;
		}
	
	}
	if( found == 1)
	cout<<"value is found at index: "<<i<<endl; 
	
	else
	cout<<"value is not found in array: "<<endl;
}